name: Weekly Grants Report

on:
  schedule:
    - cron: '0 9 * * 2'  # Every Monday at 8:00 AM UTC (adjust for your timezone) edit
  workflow_dispatch:      # Allow manual triggering
  push:
    paths:
      - Opportunity_Report.qmd
      - download_pages_and_render.R
      - email_summary_report.R
      - .github/workflows/update-report.yml

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install system dependencies for svglite
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libpng-dev \
            libtiff5-dev \
            libcairo2-dev

      - name: Install R dependencies (cached)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            readr
            plyr
            here
            lubridate
            knitr
            svglite
            kableExtra
            tibble
            httr
            curl
            blastula
            rvest
            xml2

      - name: Run R script to fetch grants and save CSV
        run: Rscript download_pages_and_render.R

      - name: Render Quarto report
        run: |
          quarto render Opportunity_Report.qmd --output-dir docs
      
      - name: Set up repo for push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      - name: Commit and push report
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add docs/
          git commit -m "Auto-update report for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Notify Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          REPORT_DATE=$(date '+%B %d, %Y')
          REPORT_URL="https://aallyn.github.io/Fed_Opportunities/docs/Opportunity_Report.html"
          MESSAGE="*GMRI Weekly Grants Report* for ${REPORT_DATE}\n${REPORT_URL}"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"${MESSAGE}\"}" \
            "$SLACK_WEBHOOK"
