name: Weekly Grants Report

on:
  schedule:
    - cron: '* * * * *'  # Every Monday at 8:00 AM UTC (adjust for your timezone)
  workflow_dispatch:      # Allow manual triggering
  push:
    paths:
      - Opportunity_Report.qmd
      - download_pages_and_render.R
      - email_summary_report.R
      - .github/workflows/update-report.yml

jobs:
  build-and-notify:
    runs-on: macos-latest  # Or 'ubuntu-latest' if your scripts don't require macOS
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("readr", "dplyr", "here", "lubridate", "knitr", "kableExtra", "tibble", "blastula", "rvest", "xml2", "here"))'
          Rscript -e 'if (!requireNamespace("quarto", quietly = TRUE)) install.packages("quarto")'

      - name: Run R script to fetch grants and save CSV
        run: Rscript download_pages_and_render.R

      - name: Render Quarto report
        run: |
          quarto render Opportunity_Report.qmd --output-dir docs

      - name: Commit and push report to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Auto-update report for $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push

      - name: Notify Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          REPORT_DATE=$(date '+%B %d, %Y')
          REPORT_URL="https://aallyn.github.io/Fed_Opportunities/docs/Opportunity_Report.html"
          MESSAGE="*GMRI Weekly Grants Report* for ${REPORT_DATE}\n${REPORT_URL}"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"${MESSAGE}\"}" \
            "$SLACK_WEBHOOK"
